### ISSUE TITLE
Full of expection!

### ISSUE THREAD

**Issue by MidaAiZ** [webweifeng/vue-mini-player#1]
正好在找轻量一点的vue视频播放插件，看到了，感觉不错！
有几个小建议：
1. 视频循环播放不起作用，浏览器：chrome(macOs)， 版本 75.0.3770.142（正式版本）(64 位）
2. 静音播放不起作用
3. 对于没有封面的视频，能否自动加载首帧作为封面
4. 自动播放不起作用（这个应该是浏览器限制导致的，不知道有没有方法可以解决）

**Comment by MidaAiZ** [comment]
另外还有个小bug：视频url后面必须带ext=.mp4这样的格式信息视频组件才会初始化，视频不会被加载也不会报错

**Comment by webweifeng** [comment]
> 正好在找轻量一点的vue视频播放插件，看到了，感觉不错！
> 有几个小建议：
> 
> 1. 视频循环播放不起作用，浏览器：chrome(macOs)， 版本 75.0.3770.142（正式版本）(64 位）
> 2. 静音播放不起作用
> 3. 对于没有封面的视频，能否自动加载首帧作为封面
> 4. 自动播放不起作用（这个应该是浏览器限制导致的，不知道有没有方法可以解决）

非常感谢使用该插件，对于以上提出意见和bug都做了修复，自动播放的话目前PC端正常，移动端暂无法实现。循环静音这些已经修复。

**Comment by Hei-Joy** [comment]
这个vue视频插件真心不错，但是还是有小小的bug，在谷歌浏览器视频海报不显示海报，移动端也不现实。
